#!/bin/bash
#PBS -N pangenome_isoniazid
#PBS -l nodes=1:ppn=3
#PBS -q cpuq
#PBS -l walltime=08:00:00

PROJ_DIR=$PBS_O_WORKDIR/pangenomes
DATA_DIR=$PROJ_DIR/data
SAMPLES_COMBINED_DIR=$DATA_DIR/samples_combined
QC_DIR=$DATA_DIR/qc

source $PBS_O_WORKDIR/env
mamba activate pangenomes

cd $SAMPLES_COMBINED_DIR
panaroo-qc -i *.gff \
           -o $QC_DIR \
           -t 1 \
           --graph_type all \
           --ref_db $DATA_DIR/refseq.genomes.k21s1000.msh
